name: cd

on:
  workflow_dispatch:
  push:
    tags: 
      - "*.*.*"

permissions:
  id-token: write

jobs:
  npm-gly-cli: 
    runs-on: ubuntu-latest   
    steps:
      -
        uses: actions/checkout@master
      - 
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      -
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      -
        run: |
          ./cli.sh cli-build
          ./cli.sh fs-replace README.md dist/README.md --format 'lua cli.lua' --replace 'gly-cli'
      -
        working-directory: ./dist
        run: |
          mv ../npm-gly-cli.json package.json
          mkdir -p bin
          npm install
      -
        working-directory: ./dist
        run: |
          npm run build
      - 
        working-directory: ./dist
        run: |
          npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
