name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua_version: ['5.1', '5.3', '5.4']
    steps:
    -
      uses: actions/checkout@master
      with:
       repository: 'rodrigodornelles/codename-videogame-engine'
       ref: 'develop'
    - 
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: ${{ matrix.lua_version }}
    -
      uses: leafo/gh-actions-luarocks@v4
    -
      run: |
        luarocks install luacov
        luarocks install luaunit
    -
      run: |
        ./cli.sh test-self --coverage
    - 
      if: (matrix.lua_version == '5.4') && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository)
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
