name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@master
    - 
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"
    -
      uses: leafo/gh-actions-luarocks@v4
    -
      run: |
        luarocks install luacov
        luarocks install luaunit
    -
      run: |
        ./cli.sh test-self --coverage
    - run: |
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
